In [2]:
import numpy as np

## 통계를 위한 연산

* 배열의 합, 평균, 표준편차, 분산, 최소값, 최대값, 누적합, 누적곱 등
* https://numpy.org/doc/stable/reference/routines.statistics.html

In [3]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [5]:
# 합과 (산술) 평균 : sum(), mean()
[arr1.sum(), arr1.mean()]

[10, 2.0]

In [6]:
# 표준편차와 분산 : std(), var()
[arr1.std(), arr1.var()]

[1.4142135623730951, 2.0]

In [7]:
# 최소값과 최대값 : min(), max()
[arr1.min(), arr1.max()]

[0, 4]

In [10]:
# 누적합과 누적곱 : cumsum(), cumprod()
arr2 = np.arange(1, 5)
arr2

array([1, 2, 3, 4])

In [11]:
# 누적합 : cumsum()
arr2.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [12]:
# 누적곱 : cumprod()
arr2.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

## 행렬연산
* 선형대수 (Linear algebra)를 위한 행렬(2차원 배열) 연산
* 행렬 곱, 전치 행렬, 역행렬, 행렬식 등
    - 행렬곱 (matrix product) : A dot(B) 혹은 np.dot(A, B)
    - 전치행렬 (transpose matrix) : A transpose() 혹은 np.transpose(A)
    - 역행렬 (inverse matrix) : np.linalg.inv(A)
    - 행렬식 (determinant) : np.linalg.det(A)

In [18]:
A = np.arange(1, 5).reshape(2, 2)
# A = np.array([1, 2], [3, 4])
# A = np.array([1, 2, 3, 4]).reshape(2, 2)
A

array([[1, 2],
       [3, 4]])

In [21]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

### 행렬의 곱

In [23]:
# 행렬의 곱 : mxn 행렬과 nxp 행렬을 곱하면 mxp 행렬 생성
A.dot(B)
# np.dot(A, B)로 사용해도 상관없음

array([[ 3,  4],
       [ 9, 10]])

### 전치행렬

In [24]:
# 전치행렬
A.transpose()

array([[1, 3],
       [2, 4]])

In [25]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

### 역행렬

In [27]:
# 역행렬 (inverse)
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
# 행렬식 (determinant_)
np.linalg.det(A)

-2.0000000000000004

In [31]:
# A * inv(A) = I (단위행렬)
np.dot(A, np.linalg.inv(A))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## Array 인덱싱(indexing)과 슬라이싱(Slicing)
* 인덱싱(indexing) : 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것
* 슬라이싱 (slicing) : 범위를 지정해 배열의 원소를 선택하는 것
    * : 연산자를 주로 사용

### 1차원 배열의 인덱싱
**배열명[위치]**
* 파이썬의 인덱싱과 동일
* 0번째로 시작함

In [32]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# 0번째 요소
arr1[0]

0

In [35]:
# 3번째 요소
arr1[3]

3

**배열명[[위치1, 위치2, ... , 위치n]]**

In [36]:
# 1, 3, 4 위치:
# shape : (m, ) => 1차원 / (m, n) => 2차원 / (m, n, p) => 3차원
# 인덱스 [] : [m] => 1차원 / [m, n] => 2차원 / [m, n, p] => 3차원
# arr1[[1,3,4]] => 3차원 배열의 위치 1면 3행 4열
# 여러 인덱스의 요소들을 지정 : 리스트로 주어야 한다

arr1[[1,3,4]]

array([1, 3, 4])

### 2차원 배열의 인덱싱
#### 배열명[행위치, 열위치]
: 2차원 배열에서 지정한 행 전체가 선택됨

In [107]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[2,3]  # 2행3열의 요소

12

In [110]:
# 0행0열 값 변경
arr2[0,0]=90

In [111]:
# 변경된 array
arr2

array([[90,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
# 두 번째 행 (1행) 선택
arr2[1]

2

#### 2차원 배열명[:, 열위치]
: 2차원 배열에서 지정한 열 전체 선택

In [49]:
arr2 = np.array([[90, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2

array([[90,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### 2차원 배열의 특정 행을 지정해서 행 전체를 변경

In [50]:
arr2[1] = np.array([-5, 1, 10, 9])

In [51]:
# 변경된 배열 확인
arr2

array([[90,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

#### 배열명[[행위치1, 행위치2, ..., 행위치n], [열위치1, 열위치2, ..., 열위치n]]
: 지정한 (행위치1, 열위치1), (행위치2, 열위치2), ... , (행위치n, 열위치n)의 원소를 가져옴

In [52]:
arr2[[0, 2], [0, 1]]

array([90, 10])

### 배열명[조건]

: 배열에서 조건을 만족하는 원소만 선택

* 10 이상만 선택

In [41]:
# 비교연산
arr2 > 10

array([False, False, False, False])

In [42]:
# 비교연산 결과를 인덱스로 지정
arr2[arr2 > 10]

array([], dtype=int32)

In [136]:
# 짝수인 원소 선택
arr2[arr2 % 2 == 0]

array([90,  2,  4,  6,  8, 10, 12])

### 1차원 배열의 슬라이싱 (Slicing)
#### 배열 [시작위치:끝위치]
: 시작위치에서 끝위치 -1에 해당하는 배열의 원소를 반환

In [53]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

### 배열 [start:end+1:step]
: start에서 end 범위까지의 자료 중 step 간격의 인덱스를 지정

In [58]:
arr1[3:9:2]
# arr1[[3, 5, 7]]와 같음

array([3, 5, 7])

In [59]:
arr1[:9:2]

array([0, 2, 4, 6, 8])

In [60]:
arr1[3::2]

array([3, 5, 7, 9])

In [61]:
arr1[::3]

array([0, 3, 6, 9])

In [62]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [63]:
arr1[::-2]

array([9, 7, 5, 3, 1])

#### 배열[:끝위치]
: 처음부터 '끝위치-1' 원소 반환

In [137]:
arr1[:3]

array([0, 1, 2])

#### 배열[시작위치 : ]
 : 시작 위치부터 마지막 원소까지 반환

In [138]:
arr1[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

#### 배열 [:]
 : 모든 원소 반환

In [139]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2차원 배열의 슬라이싱
#### 배열[행시작위치 : 행끝위치, 열시작위치 : 열끝위치]

In [140]:
arr2

array([[90,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
# 2행의 모든 요소 꺼내기
arr2[2, :]

array([ 9, 10, 11, 12])

In [142]:
arr2[2]

array([ 9, 10, 11, 12])

In [143]:
# 3열의 모든 요소 꺼내기
arr2[:, 3]

array([ 4,  8, 12])

In [145]:
# 1~2행, 1~2열의 요소 
arr2[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

### 배열[행위치][열시작위치:열끝위치]
: 특정 행을 선택한 후 열을 슬라이싱

In [70]:
arr3 = np.arange(10, 100, 10).reshape(3, 3)
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [146]:
# 1행의 0열과 1열 요소 선택
# arr3[1, :2]
arr3[1][:2]

array([40,  4])

In [73]:
# 참고. 인덱싱 예
arr3[2][1]

80

### 슬라이싱 된 배열에 값을 지정

In [79]:
# 0~1행, 1~2열의 요소 변경
arr3[:2, 1:3] = np.array([[1, 3], [4, 1]])
arr3

array([[10,  1,  3],
       [40,  4,  1],
       [70, 80, 90]])

## Array boolean 인덱싱 (Mask)
* 다차원의 인덱싱을 응용하여 boolean 인덱싱
* boolean 인덱싱을 통해 만들어낸 array를 통해 원하는 행 또는 열의 값만 뽑아냄
* 가리고 싶은 부분은 가리고, 원하는 요소만 꺼냄

In [80]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [81]:
# names 크기 확인
names.shape

(8,)

In [83]:
# 8행 4열의 실수 난수 배열 생성
data = np.random.randn(8, 4)
data

array([[ 0.38503146,  2.76741689,  0.47135393,  0.56989486],
       [-0.73386176, -2.92690171, -0.03121989, -0.08008324],
       [-0.70243678, -0.8602467 , -0.05970601, -1.65604745],
       [-1.62393663,  0.57590888, -0.1261425 , -1.43093626],
       [ 0.46863327, -0.39963237,  0.25223433,  0.15021052],
       [-1.21433119, -1.61106419,  1.35994901,  0.21035626],
       [ 0.99940229,  0.80341607,  1.10874134, -1.02295377],
       [ 0.33377691,  1.70412219, -0.8853241 , -0.53641032]])

In [84]:
# 배열 크기 확인
data.shape

(8, 4)

In [86]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_mask_Beomwoo = (names == 'Beomwoo')
names_mask_Beomwoo

array([ True,  True, False, False, False,  True, False,  True])

In [147]:
# 요소가 Beomwoo인 항목의 위치와 같은 행의 자료 가져오기
data[names_mask_Beomwoo, :]
# data[names_mask_Beomwoo] : 같은 결과

array([[ 0.38503146,  2.76741689,  0.47135393,  0.56989486],
       [-0.73386176, -2.92690171, -0.03121989, -0.08008324],
       [-1.21433119, -1.61106419,  1.35994901,  0.21035626],
       [ 0.33377691,  1.70412219, -0.8853241 , -0.53641032]])

In [89]:
# 요소가 Kim인 행의 데이터만 꺼내기
data[names=='Kim', :]

array([[-0.70243678, -0.8602467 , -0.05970601, -1.65604745]])

In [90]:
# 논리 연산을 응용하여, 요소가 Kim 또는 park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names == 'Park')]

array([[-0.70243678, -0.8602467 , -0.05970601, -1.65604745],
       [ 0.99940229,  0.80341607,  1.10874134, -1.02295377]])

### 마스크 인덱싱 문제
* 문제 1 : data array에서 0번째 열이 0보다 작은 행 데이터 가져오기

In [148]:
# 1단계. 마스크를 만든다
#        data array에서 0번째 열이 0보다 작은 요소의 boolean 값을 선택하기 위한 마스크
data[:, 0] < 0

array([False,  True,  True,  True, False,  True, False, False])

In [149]:
# 2단계. 생성된 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구함
data[data[:, 0]<0]

array([[-0.73386176, -2.92690171, -0.03121989, -0.08008324],
       [-0.70243678, -0.8602467 , -0.05970601, -1.65604745],
       [-1.62393663,  0.57590888, -0.1261425 , -1.43093626],
       [-1.21433119, -1.61106419,  1.35994901,  0.21035626]])

* 문제 2 : data array에서 0번째 열이 0보다 작은 행의 2, 3번째 열 데이터 가져오기

In [151]:
# 1. 마스크 생성 : 0번째 열의 값이 0보다 작은 행의 2, 3번째 열 값
# data[data[:, 0]<0][:, 2:4]
# data[data[:,0]<0, 2:4] 도 같은 결과가 나옴
mask = data[:, 0] < 0
mask

array([False,  True,  True,  True, False,  True, False, False])

In [152]:
# 2. 생성된 마스크로 데이터 가져오기
data[mask, 2:4]

array([[-0.03121989, -0.08008324],
       [-0.05970601, -1.65604745],
       [-0.1261425 , -1.43093626],
       [ 1.35994901,  0.21035626]])

## array에 적용되는 다양한 함수

### 하나의 array에 적용되는 함수

#### random.randn(d0, d1, ..., dn) : 표준정규난수 생성
: https://numpy.org/doc/stable/reference/random/legacy.html

In [153]:
# 5행 3열의 실수난수 배열 생성
data = np.random.randn(5, 3)
data

array([[-0.29091004, -0.35539662,  0.34928679],
       [ 0.45008819, -0.9071853 ,  1.66736655],
       [-1.19673251,  0.08437459,  0.2949771 ],
       [ 0.14522381, -0.36909487,  0.25937837],
       [-0.78050246,  1.75024199, -0.57325287]])

#### 수학 관련 함수

- 제곱근, 절대값, 삼각함수, 지수로그함수, 반올림함수 등


https://numpy.org/doc/stable/reference/routines.math.html

In [156]:
# 각 성분의 절대값 계산하기
np.abs(data)

array([[0.29091004, 0.35539662, 0.34928679],
       [0.45008819, 0.9071853 , 1.66736655],
       [1.19673251, 0.08437459, 0.2949771 ],
       [0.14522381, 0.36909487, 0.25937837],
       [0.78050246, 1.75024199, 0.57325287]])

In [157]:
# 각 성분의 제곱근 계산하기 : data ** 0.5
np.sqrt(np.abs(data))

array([[0.53936077, 0.59615151, 0.5910049 ],
       [0.67088612, 0.95246276, 1.29126548],
       [1.0939527 , 0.29047305, 0.54311795],
       [0.38108242, 0.60753179, 0.50929203],
       [0.8834605 , 1.32296712, 0.75713464]])

In [158]:
# 각 성분의 제곱 계산하기
np.square(data)

array([[0.08462865, 0.12630676, 0.12200126],
       [0.20257938, 0.82298518, 2.78011121],
       [1.4321687 , 0.00711907, 0.08701149],
       [0.02108995, 0.13623103, 0.06727714],
       [0.60918409, 3.06334702, 0.32861885]])

#### 지수함수

In [97]:
# 각 성분을 자연대수 e의 지수로 삼은 값을 계산하기
np.exp(data)

array([[ 1.46966055, 15.91746437,  1.60216195,  1.76808114],
       [ 0.48005156,  0.05356273,  0.96926242,  0.92303951],
       [ 0.49537671,  0.4230577 ,  0.94204144,  0.190892  ],
       [ 0.19712118,  1.77874645,  0.88148923,  0.23908497],
       [ 1.59780893,  0.67056652,  1.28689756,  1.16207885],
       [ 0.29690852,  0.19967501,  3.89599464,  1.23411765],
       [ 2.71665758,  2.23315652,  3.03054159,  0.3595314 ],
       [ 1.39623162,  5.49655863,  0.41258043,  0.58484389]])

### 로그함수
* 자연로그 : log()
* 상용로그 : log10()
* 밑이 2인 로그 : log2()

In [98]:
# 자연로그
np.log(abs(data))

array([[-9.54430246e-01,  1.01791436e+00, -7.52146016e-01,
        -5.62303398e-01],
       [-3.09434609e-01,  1.07394443e+00, -3.46669984e+00,
        -2.52468869e+00],
       [-3.53199876e-01, -1.50536068e-01, -2.81832253e+00,
         5.04433708e-01],
       [ 4.84853218e-01, -5.51805833e-01, -2.07034306e+00,
         3.58328959e-01],
       [-7.57934753e-01, -9.17210219e-01, -1.37739676e+00,
        -1.89571753e+00],
       [ 1.94193464e-01,  4.76894951e-01,  3.07447207e-01,
        -1.55895272e+00],
       [-5.97884414e-04, -2.18882560e-01,  1.03225448e-01,
         2.26942919e-02],
       [-1.09728245e+00,  5.33050135e-01, -1.21801483e-01,
        -6.22855889e-01]])

In [99]:
# 상용로그
np.log10(abs(data))

array([[-4.14503789e-01,  4.42074588e-01, -3.26652864e-01,
        -2.44205263e-01],
       [-1.34385743e-01,  4.66408139e-01, -1.50556861e+00,
        -1.09645837e+00],
       [-1.53392757e-01, -6.53769835e-02, -1.22398192e+00,
         2.19072776e-01],
       [ 2.10569077e-01, -2.39646229e-01, -8.99138567e-01,
         1.55620289e-01],
       [-3.29166881e-01, -3.98339337e-01, -5.98195811e-01,
        -8.23299662e-01],
       [ 8.43371499e-02,  2.07112846e-01,  1.33522626e-01,
        -6.77044565e-01],
       [-2.59657902e-04, -9.50594879e-02,  4.48302426e-02,
         9.85600573e-03],
       [-4.76543713e-01,  2.31500732e-01, -5.28977118e-02,
        -2.70502876e-01]])

In [101]:
# 밑이 2인 로그
np.log2(abs(data))     # 데이터에 음수가 있어서 abs를 해주는 것

array([[-1.37695178e+00,  1.46853999e+00, -1.08511733e+00,
        -8.11232323e-01],
       [-4.46419776e-01,  1.54937430e+00, -5.00139067e+00,
        -3.64235585e+00],
       [-5.09559710e-01, -2.17177638e-01, -4.06597993e+00,
         7.27744009e-01],
       [ 6.99495333e-01, -7.96087539e-01, -2.98687367e+00,
         5.16959412e-01],
       [-1.09346871e+00, -1.32325463e+00, -1.98716347e+00,
        -2.73494228e+00],
       [ 2.80161948e-01,  6.88013980e-01,  4.43552561e-01,
        -2.24909336e+00],
       [-8.62564880e-04, -3.15780784e-01,  1.48922842e-01,
         3.27409424e-02],
       [-1.58304395e+00,  7.69028787e-01, -1.75722395e-01,
        -8.98591102e-01]])

#### 각 성분의 부호 계산 : sign()
: + 인 경우 1, - 인 경우 -1, 0인 경우 0

In [159]:
np.sign(data)

array([[-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1., -1.]])

In [160]:
# 각 성분의 부호 계산하기 (+의 경우 1, -인 경우 -1, 0인 경우 0)
np.sign(data)

array([[-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1., -1.]])

#### 반올림 함수

In [161]:
data

array([[-0.29091004, -0.35539662,  0.34928679],
       [ 0.45008819, -0.9071853 ,  1.66736655],
       [-1.19673251,  0.08437459,  0.2949771 ],
       [ 0.14522381, -0.36909487,  0.25937837],
       [-0.78050246,  1.75024199, -0.57325287]])

In [162]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기
np.floor(data)

array([[-1., -1.,  0.],
       [ 0., -1.,  1.],
       [-2.,  0.,  0.],
       [ 0., -1.,  0.],
       [-1.,  1., -1.]])

#### Nan 여부 확인

In [164]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(data)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [165]:
# 로그변환한 배열 중 Nan 확인
np.isnan(np.log(data))

<ipython-input-165-7c22e65b5e50>:2: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(data))


array([[ True,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False,  True]])

#### 무한대(inf) 확인

In [166]:
#각 성분이 무한대인 경우 True를, 아닌 경우 False를 반환하기
np.isinf(data)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

#### 삼각함수
 : 각 성분에 대해 삼각함수 값을 계산하기 (cos, cosh, sin, sinh, tan, tanh)

In [102]:
# cos()
np.cos(data)

array([[ 0.92678662, -0.9308092 ,  0.89095429,  0.84195771],
       [ 0.74259356, -0.97704228,  0.9995127 ,  0.99679505],
       [ 0.7632701 ,  0.65225049,  0.99821813, -0.08514789],
       [-0.05311529,  0.83869768,  0.99205458,  0.13940455],
       [ 0.89218643,  0.92120409,  0.96835722,  0.9887396 ],
       [ 0.34896377, -0.04025699,  0.20928853,  0.97795659],
       [ 0.54080516,  0.69425211,  0.44578854,  0.52084674],
       [ 0.94481172, -0.13293122,  0.63303864,  0.85954874]])

In [167]:
# tan()
np.tan(data)

array([[ -0.29940414,  -0.37115633,   0.36422046],
       [  0.48316384,  -1.27892402, -10.32294873],
       [ -2.54747384,   0.08457539,   0.30384121],
       [  0.14625342,  -0.38682224,   0.26535603],
       [ -0.99025622,  -5.51277354,  -0.64556743]])

#### Sums(), products, differences 함수

In [106]:
data

array([[ 0.38503146,  2.76741689,  0.47135393,  0.56989486],
       [-0.73386176, -2.92690171, -0.03121989, -0.08008324],
       [-0.70243678, -0.8602467 , -0.05970601, -1.65604745],
       [-1.62393663,  0.57590888, -0.1261425 , -1.43093626],
       [ 0.46863327, -0.39963237,  0.25223433,  0.15021052],
       [-1.21433119, -1.61106419,  1.35994901,  0.21035626],
       [ 0.99940229,  0.80341607,  1.10874134, -1.02295377],
       [ 0.33377691,  1.70412219, -0.8853241 , -0.53641032]])

In [103]:
# 전체 성분의 합을 계산
np.sum(data)

-3.740786677855099

In [105]:
# 열 간의 합을 계산 (axis=0)
np.sum(data, axis=0)

array([-2.08772242,  0.05301905,  2.08988611, -3.79596941])

In [168]:
# 행 간의 합을 계산 (axis=1)
np.sum(data, axis=1)

array([-0.29701988,  1.21026944, -0.81738081,  0.0355073 ,  0.39648666])

#### 평균(mean), 표준편차(std), 분산(var)

In [ ]:
# 전체 성분의 평균 계산
np.mean(data)

In [ ]:
# 행 간의 평균 계산 axis = 1
np.mean(data, axis=1)

In [ ]:
# 열별로 평균 계산 axis = 0
np.mean(data, axis=0)

In [ ]:
# 전체 성분의 표준편차 계산
np.std(data)

In [ ]:
# 월별 표준편차 계산
np.std(data, axis=0)

In [ ]:
# 행별 표준편차 계산
np.std(data, axis=1)

#### 최대값(max), 최소값(min)

In [ ]:
# 열방향에서 최소값
np.min(data, axis=0)

### 최대값, 최소값 위치 인덱스 : argmax(), argmin()

In [112]:
data

array([[ 0.38503146,  2.76741689,  0.47135393,  0.56989486],
       [-0.73386176, -2.92690171, -0.03121989, -0.08008324],
       [-0.70243678, -0.8602467 , -0.05970601, -1.65604745],
       [-1.62393663,  0.57590888, -0.1261425 , -1.43093626],
       [ 0.46863327, -0.39963237,  0.25223433,  0.15021052],
       [-1.21433119, -1.61106419,  1.35994901,  0.21035626],
       [ 0.99940229,  0.80341607,  1.10874134, -1.02295377],
       [ 0.33377691,  1.70412219, -0.8853241 , -0.53641032]])

In [116]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환 (argmin, argmax)
[np.argmax(data), np.argmin(data)]

[1, 5]

In [117]:
# 행방향으로 최대값이 위치한 인덱스 반환
np.argmax(data, axis=1)

array([1, 2, 2, 1, 0, 2, 2, 1], dtype=int64)

### 누적합(cumsum), 누적곱(cumprod)

In [118]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱 계산 (cumsum, cumprod)
np.cumsum(data)

array([ 0.38503146,  3.15244835,  3.62380228,  4.19369714,  3.45983538,
        0.53293367,  0.50171378,  0.42163054, -0.28080624, -1.14105294,
       -1.20075896, -2.85680641, -4.48074303, -3.90483416, -4.03097666,
       -5.46191292, -4.99327965, -5.39291202, -5.14067769, -4.99046718,
       -6.20479837, -7.81586256, -6.45591355, -6.24555729, -5.246155  ,
       -4.44273893, -3.33399759, -4.35695136, -4.02317445, -2.31905225,
       -3.20437636, -3.74078668])

In [119]:
# 열 기준 누적합
np.cumsum(data, axis = 0)

array([[ 0.38503146,  2.76741689,  0.47135393,  0.56989486],
       [-0.3488303 , -0.15948482,  0.44013404,  0.48981162],
       [-1.05126708, -1.01973152,  0.38042803, -1.16623583],
       [-2.67520371, -0.44382265,  0.25428553, -2.59717209],
       [-2.20657044, -0.84345502,  0.50651985, -2.44696158],
       [-3.42090163, -2.45451921,  1.86646887, -2.23660532],
       [-2.42149933, -1.65110315,  2.97521021, -3.25955909],
       [-2.08772242,  0.05301905,  2.08988611, -3.79596941]])

In [121]:
# 누적곱
np.cumprod(data)

array([ 3.85031455e-01,  1.06554255e+00,  5.02247674e-01,  2.86228366e-01,
       -2.10052052e-01,  6.14801710e-01, -1.91940426e-02,  1.53712112e-03,
       -1.07973041e-03,  9.28834522e-04, -5.54570069e-05,  9.18394348e-05,
       -1.49141422e-04, -8.58918685e-05,  1.08346150e-05, -1.55036435e-05,
       -7.26552317e-06,  2.90353827e-06,  7.32372020e-07,  1.10009979e-07,
       -1.33588549e-07,  2.15219728e-07,  2.92687856e-07,  6.15687220e-08,
        6.15319220e-08,  4.94357347e-08,  5.48114430e-08, -5.60695720e-08,
       -1.87147284e-08, -3.18921839e-08,  2.82349191e-08, -1.51455020e-08])

In [122]:
np.cumprod(data, axis=1)

array([[ 0.38503146,  1.06554255,  0.50224767,  0.28622837],
       [-0.73386176,  2.14794124, -0.06705849,  0.00537026],
       [-0.70243678,  0.60426892, -0.03607849,  0.05974769],
       [-1.62393663, -0.93523952,  0.11797345, -0.16881249],
       [ 0.46863327, -0.18728103, -0.0472387 , -0.00709575],
       [-1.21433119,  1.9563655 ,  2.66055733,  0.55966488],
       [ 0.99940229,  0.80293586,  0.89024818, -0.91068273],
       [ 0.33377691,  0.56879664, -0.50356937,  0.27011981]])

In [123]:
# 전체 성분에 대해서 오름차순으로 정렬
np.sort(data)

array([[ 0.38503146,  0.47135393,  0.56989486,  2.76741689],
       [-2.92690171, -0.73386176, -0.08008324, -0.03121989],
       [-1.65604745, -0.8602467 , -0.70243678, -0.05970601],
       [-1.62393663, -1.43093626, -0.1261425 ,  0.57590888],
       [-0.39963237,  0.15021052,  0.25223433,  0.46863327],
       [-1.61106419, -1.21433119,  0.21035626,  1.35994901],
       [-1.02295377,  0.80341607,  0.99940229,  1.10874134],
       [-0.8853241 , -0.53641032,  0.33377691,  1.70412219]])

In [ ]:
# 전체 성분에 대해서 [::-1]를 적용 : 정렬 후 마지막행부터 표시
np.sort(data)[::-1]

In [ ]:
data

In [ ]:
# 행방향으로 오름차순으로 정렬
np.sort(data, axis=1)

In [ ]:
# 열방향으로 오름차순으로 정렬
np.sord(data, axis=0)

### 두 개의 array에 적용되는 함수

In [125]:
data1 = np.random.randn(5, 3)

In [131]:
data2 = np.random.randn(5, 3)

In [132]:
# 5행 3열의 실수난수 배열 생성
data1

array([[ 0.6898113 ,  0.51392087, -1.16019926],
       [ 0.01737316,  1.41951464,  1.77051219],
       [-0.33939534, -1.29221421, -0.12017398],
       [ 0.63097473, -0.7410996 ,  0.88028639],
       [-0.61845776, -0.05363887, -0.51441402]])

In [133]:
data2

array([[-0.28633583, -1.03754179, -1.17135559],
       [-0.24256865, -0.00868906,  1.31340505],
       [-0.85424227, -0.01158568, -0.63529348],
       [ 0.78987822, -1.30730964, -1.13731616],
       [ 1.54684403, -0.16708619,  0.29406844]])

### 두 개의 array에 대해 동일한 위치의 성분끼리 연산
* add(), subtract(), multiply(), divide()

In [ ]:
# 두 배열의 합

In [ ]:
# 두 배열의 차

In [ ]:
# 두 배열의 곱

In [ ]:
# 두 배열의 나눗셈

* 최대값 또는 최소값 계산
: maximum(), minimum()

In [ ]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여
# 최대값 또는 최소값 계산하기 (maximum, minimum)
np.maximum(data1, data2)

In [ ]:
# 최대값 또는 최소값 계산하기 (maximum, minimum)
