# **Chapter 2. 파이썬 빅데이터 분석 패키지**

## 1. 넘파이 (Numpy)

### (1) 넘파이 (Numpy) 개요

### (2) 넘파이 배열 생성

#### 212-01 넘파이 임포트

In [ ]:
import numpy as np

#### 212-02 넘파이 배열 형태

In [ ]:
a1 = np.array([1, 2, 3])
print(a1)
print('array1 type : ', type(a1))
print('array1 shape : ', a1.shape)

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print('array2 type : ', type(a2))
print('array2 shape : ', a2.shape)

a3 = np.array([[1, 2, 3]])
print(a3)
print('array3 type : ', type(a3))
print('array3 shape : ', a3.shape)

[1 2 3]
array1 type :  <class 'numpy.ndarray'>
array1 shape :  (3,)
[[1 2 3]
 [4 5 6]]
array2 type :  <class 'numpy.ndarray'>
array2 shape :  (2, 3)
[[1 2 3]]
array3 type :  <class 'numpy.ndarray'>
array3 shape :  (1, 3)


#### 212-03 넘파이 배열 차원

In [ ]:
print('array1 dim :', a1.ndim)
print('array2 dim :', a2.ndim)
print('array3 dim :', a3.ndim)

array1 dim : 1
array2 dim : 2
array3 dim : 2


#### 212-04 넘파이 arange 함수 기본

In [ ]:
a = np.arange(20) 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 212-05 넘파이 arange 함수 응용

In [ ]:
a = np.arange(1, 20, 3) 
print(a)

[ 1  4  7 10 13 16 19]


### (3) 넘파이 배열 초기화

#### 213-01 넘파이 zeros, ones 함수

In [ ]:
zero_a = np.zeros((2,5)) 
one_a = np.ones((3,4)) 

print(zero_a)
print(one_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 213-02 넘파이 zeros_like 함수

In [ ]:
zero_b = np.zeros_like(one_a)
print(zero_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 213-03 넘파이 ones_like 함수

In [ ]:
one_b = np.ones_like(zero_a)
print(one_b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 213-04 넘파이 full, random 함수

In [ ]:
full_a = np.full((4, 3),9) 
random_a = np.random.random((3, 4)) 

print(full_a)
print(random_a)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.41176928 0.37840885 0.74979053 0.15214094]
 [0.8248999  0.04586987 0.87185399 0.18875634]
 [0.53343751 0.54662109 0.83876615 0.31865313]]


#### 213-05 넘파이 eye 함수

In [ ]:
eye_a = np.eye(4) 
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### (4) 넘파이 배열 크기 변형

#### 214-01 넘파이 reshape 함수 기본

In [ ]:
array1 = np.arange(12)
print('array1:\n', array1)

array2 = array1.reshape(3,4)
print('array2:\n', array2)

array3 = array1.reshape(3,4,order='F')
print('array3:\n', array3)

array1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
array2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array3:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


#### 214-02 넘파이 reshape 함수 응용

In [ ]:
array1 = np.arange(10)
array2 = array1.reshape(-1, 5)

print(array2)
print('array2 dim : ', array2.ndim)
print('array2 shape : ', array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 dim :  2
array2 shape :  (2, 5)


#### 214-03 넘파이 reshape 함수 다차원 변형

In [ ]:
array1 = np.arange(12)
array2 = array1.reshape(2,3,2, order='F')

print(array2)
print('array2 dim : ', array2.ndim)
print('array2 shape : ', array2.shape)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
array2 dim :  3
array2 shape :  (2, 3, 2)


#### 214-04 넘파이 flatten 함수 1차원 변형

In [ ]:
array3 = array2.flatten()
print(array3)

[ 0  6  2  8  4 10  1  7  3  9  5 11]


### (5) 넘파이 배열 데이터 추출하기

#### 215-01 넘파이 1차원 배열 단일값 추출

In [ ]:
array1 = np.arange(1, 10)
print('array1 : ', array1)

value1 = array1[2]
value2 = array1[-2]

print(value1)
print(value2)

array1 :  [1 2 3 4 5 6 7 8 9]
3
8


#### 215-02 넘파이 다차원 배열 단일값 추출

In [ ]:
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print('array2 :\n', array2)

value1 = array2[0,0]
value2 = array2[-1, -1]
value3 = array2[-1, -2]

print(value1)
print(value2)
print(value3)

array2 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8


#### 215-03 넘파이 1차원 배열 슬라이싱 추출

In [ ]:
array1 = np.arange(1, 10)
array2 = array1[0:3]
array3 = array1[:3]
array4 = array1[3:]

print(type(array2))
print(array2)
print(array3)
print(array4)

<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]


#### 215-04 넘파이 다차원 배열 슬라이싱 추출

In [ ]:
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print('array2 : \n', array2)

print('array2[0:2, 0:2]\n', array2[0:2, 0:2])
print('array2[1:3, 0:3]\n', array2[1:3, 0:3])
print('array2[:2, 1:]\n', array2[:2, 1:])
print('array2[:2, 0]\n', array2[:2, 0])

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2]
 [[1 2]
 [4 5]]
array2[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2[:2, 1:]
 [[2 3]
 [5 6]]
array2[:2, 0]
 [1 4]


### (6) 넘파이 선형대수 기본연산

#### 216-01 넘파이 행렬 내적 계산

In [ ]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

dot_array = np.dot(array1, array2)
print(dot_array)

[[ 58  64]
 [139 154]]


#### 216-02 넘파이 전치 행렬 계산

In [ ]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
transpose_array = np.transpose(array1)

print(transpose_array)

[[1 4]
 [2 5]
 [3 6]]


### (7) 넘파이 기술 통계

#### 217-01 배열 데이터 개수 계산

In [ ]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

len(x)

26

#### 217-02 평균, 분산, 표준편차 계산

In [ ]:
print(np.mean(x))
print(np.var(x))
print(np.std(x))

4.8076923076923075
115.23224852071006
10.734628476137871


#### 217-03 최대값, 최소값, 중앙값 계산

In [ ]:
print(np.max(x))
print(np.min(x))
print(np.median(x))

23
-24
5.0


#### 217-04 사분위수 계산

In [ ]:
print(np.percentile(x, 25))
print(np.percentile(x, 50))
print(np.percentile(x, 75))

0.0
5.0
10.0
